# FROM node:14
# RUN mkdir -p /app
# WORKDIR /app
# COPY package.json /app
# RUN npm install
# COPY . /app
# RUN npm run build --prod

# FROM nginx:alpine
# COPY --from=0 /app/dist/ /usr/share/nginx/html


# Usar la imagen de node 14 como base
FROM node:14

WORKDIR /app

# Copiar los archivos de la aplicación en la imagen Docker
COPY . .

# Instalar las dependencias de la aplicación
RUN npm install
# RUN cd dist/space-war-front-web/
# RUN npm start

# Iniciar la aplicación en el puerto 4200
# CMD ng serve --proxy-config ./src/proxy.conf.json --port 4200
# RUN ng serve --proxy-config ./src/proxy.conf.json
# RUN npm run build --prod

